[build-system]
requires = ["setuptools >= 62"]
build-backend = "setuptools.build_meta"

[project]
name = "helloworld"
dynamic = ["version"]

python_requires=">=3.9"

[project.scripts]
helloworld_in_python = "helloworld.main:main"